name: deploy optimade.science

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: tilde-lab/optimade.science

      - name: Install
        run: |
          npm install

      - name: Prefetch providers
        run: |
          npm run prefetch

      - name: Build
        run: |
          npm run build
          npm list

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
